package com.elong.pb.newdda.client.jdbc;

import com.elong.pb.newdda.client.jdbc.adapter.AbstractConnectionAdapter;
import com.elong.pb.newdda.client.router.SqlRouterEngine;
import com.elong.pb.newdda.client.router.result.router.SqlStatementType;
import com.elong.pb.newdda.client.router.rule.ShardingRule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

/**
 * 分区的链接
 * User: zhangyong
 * Date: 2016/3/31
 * Time: 18:53
 * To change this template use File | Settings | File Templates.
 */
public class ShardingConnection extends AbstractConnectionAdapter {

    private final static Logger logger = LoggerFactory.getLogger(ShardingConnection.class);

    private final ShardingRule shardingRule;

    private SqlRouterEngine sqlRouterEngine;

    private final Map<String, Connection> connectionMap = new HashMap<String, Connection>();

    public ShardingConnection(ShardingRule shardingRule) {
        this.shardingRule = shardingRule;
        this.sqlRouterEngine = new SqlRouterEngine(shardingRule);
    }

    @Override
    protected Collection<Connection> getConnections() {
        return connectionMap.values();
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new ShardingStatement(this, sqlRouterEngine);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return null;
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        return null;
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return null;
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return null;
    }


    //======================================================== 通过数据源名称 以及 sql类型取得链接 ========================================================
    public Connection getConnection(final String dataSourceName, final SqlStatementType sqlStatementType) throws SQLException {
        Connection connection = null;
        return connection;
    }


}
